services:
  mydb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mydb_data:/var/lib/mysql
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql

  myapp:
    build:
      context: ./docker/php
    user: dev
    ports:
      - 8000:80
      - 5173:5173
    volumes:
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/terminal/.bashrc:/home/dev/.bashrc
      - ./docker/terminal/git-prompt.sh:/home/dev/git-prompt.sh
      - ./src:/var/www/html
      # Share SSH keys from WSL2 (only if directory exists)
      - ~/.ssh:/home/dev/.ssh:ro
      # 各アプリごとのvendorとnode_modulesをvolumeにする
      - laravel_react_base_vendor:/var/www/html/laravel-react-base/vendor
      - laravel_react_base_node:/var/www/html/laravel-react-base/node_modules

  phpmyadmin:
    depends_on:
      - mydb
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mydb
      PMA_USER: admin
      PMA_PASSWORD: secret
      MEMORY_LIMIT: 256M
      UPLOAD_LIMIT: 128M
    volumes:
      - phpmyadmin_session_laravel:/sessions

  mailhog:
    image: mailhog/mailhog
    container_name: "mailhog"
    ports:
      - 8025:8025
      - 1025:1025

networks:
  laravel-net:

volumes:
  mydb_data:
  phpmyadmin_session_laravel:
  laravel_react_base_vendor:
  laravel_react_base_node:
